packages: []
catalogs:
  framework:
    '@mdx-js/loader': ^3.1.1
    '@mdx-js/react': ^3.1.1
    '@next/mdx': ^15.5.4
    '@shikijs/rehype': ^3.13.0
    '@shikijs/transformers': ^3.13.0
    '@tailwindcss/postcss': ^4.1.14
    '@types/node': ^24.7.0
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.1
    eslint-config-next: ^15.5.4
    next: ^15.5.4
    next-mdx-remote: ^5.0.0
    react: ^19.2.0
    react-dom: ^19.2.0
    rehype-autolink-headings: ^7.1.0
    tailwindcss: ^4.1.14
    typescript: ^5.9.3
    zod: ^4.1.12
  ui:
    '@radix-ui/react-avatar': ^1.1.10
    '@radix-ui/react-slot': ^1.2.3
    lucide-react: ^0.545.0
  utils:
    '@eslint/eslintrc': ^3.3.1
    '@netlify/plugin-nextjs': ^5.13.5
    animejs: ^4.2.2
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    eslint: ^9.37.0
    fuse.js: ^7.1.0
    gray-matter: ^4.0.3
    next-themes: ^0.4.6
    prettier: ^3.6.2
    react-icons: ^5.5.0
    rehype-pretty-code: ^0.14.1
    rehype-slug: ^6.0.0
    shiki: ^3.13.0
    tailwind-merge: ^3.3.1
    tw-animate-css: ^1.4.0
